### ISSUE TITLE
mid

### ISSUE THREAD

**Issue by hudson-liu** [Andallfor/andallfor-home#1]
mid website bro
consider getting better perchance

**Comment by Andallfor** [comment]
![image](https://github.com/user-attachments/assets/0e83afd0-526e-42a6-ac40-7f7e98357134)

**Comment by Andallfor** [comment]
![image](https://github.com/user-attachments/assets/6fca6e95-5367-45cd-bc20-dd4892fcf548)
(u also prob wanna offset it slightly from the edge of the screen)

**Comment by hudson-liu** [comment]
bruh aint no way

also yeah i literally just copied some random dude's template and changed the colors lmao

**Comment by Andallfor** [comment]
Possible duplicate of https://github.com/Hudson-Liu/Personal-Website/issues/1
Issue closed.
